name: Build and Deploy API Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
        
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build  API
      run: |
        dotnet clean ./DotNetBucketry/DotNetBucketry.csproj
        dotnet build ./DotNetBucketry/DotNetBucketry.csproj --configuration Release

    - name: Generate Swagger JSON
      run: |
          dotnet tool install -g swashbuckle.aspnetcore.cli
          export PATH="$PATH:/home/runner/.dotnet/tools"
          swagger tofile --output swagger.json ./DotNetBucketry/bin/Release/net8.0/DotNetBucketry.dll v1

    - name: Install Redoc CLI
      run: npm install -g @redocly/cli
      
    - name: Generate Static HTML Documentation
      run: redocly build-docs swagger.json -o api-docs.html

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-docs
        path: api-docs.html
